Create basic workflows to test build frontend and backend
Like-Home/LikeHome pull request #7
Opened 2023-03-01 02:53 UTC by mruiz42

These files will attempt to build and  compile the code that can be run during PR and merge to main. This will help us determine if we are committing quality and working code to main branch while saving us time manually testing code ourselves. We will need to revisit this file once we get some unit tests running.

2023-03-01 03:40 UTC, NoahCardoza requested changes

2023-03-01 03:40 UTC, NoahCardoza commented on .github/workflows/test-backend.yml
> +      - name: Run flask migrations
```suggestion
      - name: Run Django migrations
```

2023-03-01 03:40 UTC, NoahCardoza commented on .github/workflows/test-backend.yml
> +          source .venv/bin/activate
Maybe we could call `make format` and `make lint`? Just so if those change we won't have to update this?

2023-03-01 03:43 UTC, mruiz42 commented on .github/workflows/test-backend.yml
> +          source .venv/bin/activate
I am not sure it is necessary, since it won't make any change to the code post-commit? We should use commit-hooks to apply linting.

Also, not sure that make is installed in the workflow vm.

2023-03-01 04:06 UTC, NoahCardoza approved these changes
LGTM

2023-03-04 06:18 UTC, AlpyneDreams approved these changes
lgtm

2023-03-04 06:37 UTC, merged